name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar calidad código con flake8
        run: |
          flake8 src/ --max-line-length=100 --statistics --count
      
      - name: Ejecutar Pytest con cobertura
        run: |
          pytest --cov=src --cov-report=term --cov-report=html --html=report.html --junitxml=report.xml tests/test_belly.py --maxfail=1 --disable-warnings -q

  behave:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Behave @spanish
        run: behave --tags=@spanish

      - name: Ejecutar Behave @english
        run: behave --tags=@english

      - name: Prueba especial 1000 pepinos
        run: |
          echo "Iniciando prueba"
          start=$(date +%s)
          behave -n "Comer 1000 pepinos y esperar 10 horas"
          end=$(date +%s)
          duracion=$((end - start))
          echo "Prueba completada en $duracion s"
          if [ "$duracion" -gt 10 ]; then
            echo "La prueba tardó demasiado"
            exit 1
          fi

      - name: Ejecutar pruebas @issue1
        run: behave --tags=@issue1
